name: AnneLigthart.com
favicon: null
layout_spectrum: 0.85371
typography_spectrum: 0.999
title: AnneLigthart.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000002'
    - '#947661'
    - '#fefff8'
    - '#dfba8f'
    - '#45a1d1'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
