name: AnneLigthart.com
favicon: null
layout_spectrum: 0.74649
typography_spectrum: 0.7878001211211085
title: AnneLigthart.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#cdc5c4'
    - '#637a6e'
    - '#5d4420'
    - '#0d0000'
  brandStrength: 0.5
  lightness: 0.47809103899635375
  saturation: 0.5
  rhythmicContrast: 0.7132301931269467
purpose: []
