name: AnneLigthart.com
favicon: null
layout_spectrum: 0.7485
typography_spectrum: 0.12525
title: AnneLigthart.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#848fa2'
    - '#e7e8ea'
    - '#31659f'
    - '#90c2f4'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.625
  rhythmicContrast: 1
purpose: []
