name: AnneLigthart.com
favicon: null
layout_spectrum: 0
typography_spectrum: 0.15331
title: AnneLigthart.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5e6d1c'
    - '#8f9c44'
    - '#f7f8f2'
    - '#bfc946'
    - '#f6f75e'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.875
  rhythmicContrast: 0
purpose: []
