name: AnneLigthart.com
favicon: null
layout_spectrum: 0.2495
typography_spectrum: 0.12525
title: AnneLigthart.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#848fa2'
    - '#e7e8ea'
    - '#31659f'
    - '#90c2f4'
  brandStrength: 0.8125
  lightness: 0.375
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
