name: AnneLigthart.com
favicon: null
layout_spectrum: 0
typography_spectrum: 0.999
title: AnneLigthart.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b091be'
    - '#bfd4db'
    - '#000700'
    - '#444000'
    - '#eb4b44'
  brandStrength: 0.4375
  lightness: 0.4375
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
