name: AnneLigthart.com
favicon: null
layout_spectrum: 1
typography_spectrum: 0.29457
title: AnneLigthart.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dbd1d0'
    - '#f73414'
    - '#00a4b1'
    - '#dc7b64'
    - '#453214'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
