name: AnneLigthart.com
favicon: null
layout_spectrum: 0.2495
typography_spectrum: 1
title: AnneLigthart.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#180f0a'
    - '#4c5604'
    - '#bda1df'
    - '#857a3f'
    - '#e9d1e9'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
