name: AnneLigthart.com
favicon: null
layout_spectrum: 0.74649
typography_spectrum: 0.7878001211211085
title: AnneLigthart.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#120403'
    - '#fe8524'
    - '#8a1b00'
    - '#e14703'
    - '#fffa87'
  brandStrength: 0.5
  lightness: 0.47809103899635375
  saturation: 0.375
  rhythmicContrast: 0.7132301931269467
purpose: []
