name: AnneLigthart.com
favicon: null
layout_spectrum: 0.49198
typography_spectrum: 1
title: AnneLigthart.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#c6c6c6'
    - '#3b3b3b'
    - '#585858'
    - '#888888'
  brandStrength: 0.1875
  lightness: 0.25
  saturation: 0.75
  rhythmicContrast: 0
purpose: []
