name: AnneLigthart.com
favicon: null
layout_spectrum: 0.49198
typography_spectrum: 1
title: AnneLigthart.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000026'
    - '#5c5751'
    - '#f6b49a'
    - '#a82249'
    - '#83795f'
  brandStrength: 0.625
  lightness: 0.25
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
