name: AnneLigthart.com
favicon: null
layout_spectrum: 1
typography_spectrum: 0.29457
title: AnneLigthart.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a6a9b0'
    - '#5e6d4c'
    - '#c1c3ce'
    - '#3c4725'
    - '#1d281a'
  brandStrength: 0.125
  lightness: 0.125
  saturation: 0.125
  rhythmicContrast: 0.25
purpose: []
