name: AnneLigthart.com
favicon: null
layout_spectrum: 0.49198
typography_spectrum: 1
title: AnneLigthart.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7b976e'
    - '#090909'
    - '#493500'
    - '#6e5d28'
    - '#fbca86'
  brandStrength: 0.1875
  lightness: 0.25
  saturation: 0.75
  rhythmicContrast: 0
purpose: []
