name: AnneLigthart.com
favicon: null
layout_spectrum: 0.498
typography_spectrum: 0.15331
title: AnneLigthart.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfcfc'
    - '#030605'
    - '#b2a79f'
    - '#8b8680'
    - '#4f463f'
  brandStrength: 0.375
  lightness: 0.3125
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
