name: AnneLigthart.com
favicon: null
layout_spectrum: 1
typography_spectrum: 0.29457
title: AnneLigthart.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#100806'
    - '#a5875f'
    - '#ffffff'
    - '#7e471f'
    - '#e4b79b'
  brandStrength: 0.75
  lightness: 0.375
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
