name: AnneLigthart.com
favicon: null
layout_spectrum: 0.5
typography_spectrum: 0.15331
title: AnneLigthart.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#544433'
    - '#8b6d4b'
    - '#9f8f76'
    - '#dbc4a5'
  brandStrength: 0.3125
  lightness: 0.3125
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
