name: AnneLigthart.com
favicon: null
layout_spectrum: 0.18737
typography_spectrum: 0.15331
title: AnneLigthart.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c9d9b5'
    - '#afa864'
    - '#4c4d41'
    - '#191514'
    - '#fefffa'
  brandStrength: 0.375
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
