name: AnneLigthart.com
favicon: null
layout_spectrum: 0.39378
typography_spectrum: 0.15331
title: AnneLigthart.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#794855'
    - '#ffecca'
    - '#ffc16c'
    - '#b58857'
    - '#bebecc'
  brandStrength: 0.25
  lightness: 0.3125
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
