name: AnneLigthart.com
favicon: null
layout_spectrum: 0.43788
typography_spectrum: 0.15331
title: AnneLigthart.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f5f5f5'
    - '#887e75'
    - '#382f26'
    - '#b13733'
    - '#0a716a'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
