name: AnneLigthart.com
favicon: null
layout_spectrum: 0.49198
typography_spectrum: 0.50601
title: AnneLigthart.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f3f3f3'
    - '#949a9a'
    - '#f3a873'
    - '#a76333'
    - '#3f0505'
  brandStrength: 0.625
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
