name: AnneLigthart.com
favicon: null
layout_spectrum: 0.76253
typography_spectrum: 0.12525
title: AnneLigthart.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d0653'
    - '#fcef53'
    - '#cf4c52'
    - '#f1a552'
    - '#761453'
  brandStrength: 0.8125
  lightness: 0.375
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
