name: AnneLigthart.com
favicon: null
layout_spectrum: 0.39379
typography_spectrum: 0.29559
title: AnneLigthart.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#795843'
    - '#8a7e76'
    - '#da9a63'
    - '#e0e0e2'
    - '#9acdff'
  brandStrength: 0
  lightness: 0.75
  saturation: 0.8125
  rhythmicContrast: 0
purpose: []
